### ISSUE TITLE
Installing v1.2.2 re-installs wrong version of Media extension

### ISSUE THREAD

**Issue by mhmli** [fabarea/infinite_scroll_gallery#4]
If I install the current version of http://typo3.org/extensions/repository/view/media (v2.01), then install infinite_scroll_gallery, the Media extension is modified. It would appear that infinite_scroll_gallery over-writes media v2 with v1.0.

**Comment by fabarea** [comment]
A lot of time has passed since... In the process of refactoring the extension.
